### ISSUE TITLE
V1 PixelBots is crashing on the preview screen when creating a reading challenge

### ISSUE THREAD

**Issue by ovanegas** [9dots/pixelBots#478]
When I click "Next" on the Create screen it takes me to the Preview screen and freezes up.
![screen shot 2018-04-27 at 12 04 07 pm](https://user-images.githubusercontent.com/20323588/39380528-b9f15d00-4a13-11e8-87ca-b260314ea9fa.png)

**Comment by amandatrock** [comment]
Hey @danleavitt0 , Oscar would like to prioritize this bug if possible, as it's preventing him from creating playlists.

**Comment by danleavitt0** [comment]
@amandatrock this should be fixed as of yesterday.
