### ISSUE TITLE
v1 PixelBots: hidden code can be selected (then deleted, or copy-and-pasted, or…?)

### ISSUE THREAD

**Issue by julescubtree** [9dots/pixelBots#484]
Is this intended behavior?

On a playlist such as [this one](http://v1.pixelbots.io/D6GEB), a user can select hidden code in one of two ways:

1. using the select all tool
2. adding code to the end of the program (which will be after the hidden code), then clicking on on lines before and after hidden code

The code can then be deleted. It also can be copied and pasted, though the code is still hidden when pasted.

**Comment by danleavitt0** [comment]
Definitely a bug. We were actually planning on removing hidden code from the platform for now.
