### ISSUE TITLE
trying to edit a specific playlist causes the site to freeze

### ISSUE THREAD

**Issue by pollysmith** [9dots/pixelBots#487]
I created a demo playlist with functions and I noticed that I forgot to enable arguments, each time I tried to do this, I am able to click the enable button but when I click "Next" the entire site freezes. I'm stuck on the "options" tab and unable to go to the "create" or "preview." When I click Next, the site freezes; even when clicking home, courses, search, nothing works or loads. I have to close the tab and reopen pixelbots. 

I've created copies of the same challenge and playlist, and used my personal account instead of the getcoding account to see if that would work, but so far it's stuck.  

http://v1.pixelbots.io/9MN6N

**Comment by danleavitt0** [comment]
@pollysmith Please add the link to the edit url when you are trying to update the challenge.

**Comment by pollysmith** [comment]
https://v1.pixelbots.io/edit/-LC5L6KFAnOO4FoPHEH-/create
